(add-to-list 'load-path "~/.emacs.d/plugins/centaur-tabs/")
(require 'centaur-tabs)
(centaur-tabs-mode t)
(centaur-tabs-headline-match)
(setq centaur-tabs-style "bar")
(setq centaur-tabs-height 32)
(setq centaur-tabs-set-icons t)
(setq centaur-tabs-plain-icons t)
(setq centaur-tabs-gray-out-icons 'buffer)
(setq centaur-tabs-set-bar 'over)
(setq centaur-tabs-close-button "×")
(setq centaur-tabs-set-modified-marker t)
(setq centaur-tabs-modified-marker "⚬")
;; :bind
;; ("C-<prior>" . centaur-tabs-backward)
;; ("C-<next>" . centaur-tabs-forward)
